@startuml

title : IntelliJ の PlantUML Plugin のアクティビティ図のデフォルト

(*)  --> "check input"
If "input is verbose" then
--> [Yes] "turn on verbosity"
--> "run command"
else
--> "run command"
Endif
-->(*)
@enduml
